### ISSUE TITLE
When mps set to non-1 minecrarts don't go up

### ISSUE THREAD

**Issue by Behoston** [rmellis/MinecartSpeedPlus#1]
![image](https://user-images.githubusercontent.com/7823689/141659901-266d4931-5dfa-4bc9-9dde-1c52b9240410.png)
When MSP=1 minecart go up to marked point, when 4 or 3.99 it stops just before ramp.

Minecraft 1.17.1 running on paper spigot

**Comment by rmellis** [comment]
Missed this issue, sorry its so late. Patched by pr, closing
