### ISSUE TITLE
Update to 1.19

### ISSUE THREAD

**Issue by quick007** [rmellis/MinecartSpeedPlus#3]
Hello! I am super excited to try out this plugin on my server, but unfortunately, it doesn't support 1.19. Can you update it to 1.19 please?

**Comment by 21mac** [comment]
There is just one typo in the source code, that is why it can't be compiled.

you can download the compiled jar here:
https://www.load.to/9tB7mKobp8/MSP1.19.jar

**BUT** I myself give you the advice to not trust random people's download links.
I know that I did not upload harmful software but you don't know this.

So it would be better if you compiled it by yourself.
Where are you stuck at?

**Comment by rmellis** [comment]
A pr was recently merged to bring things more upto date, hopefully this will help with 1.19, there are some good forks people have done too that are worth checking out, this one had 1.19 support added along with some improvements https://github.com/powerje/MinecartSpeedPlus
